export const SETTINGS_STORE = "deepagent-code.settings"
export const DEFAULT_SERVER_URL_KEY = "defaultServerUrl"
export const WSL_SERVERS_KEY = "wslServers"
export const PINCH_ZOOM_ENABLED_KEY = "pinchZoomEnabled"
export const PREVENT_SLEEP_KEY = "preventSleep"
